dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=2.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install codecov coverage
script:
  - coverage run manage.py test
after_success: 
  - codecov
